app: student-ai-mentor
primary_region: iad  # Ashburn, Virginia

build:
  dockerfile: Dockerfile

env:
  HOST: 0.0.0.0
  PORT: 8000

http_service:
  internal_port: 8000
  force_https: true
  auto_start_machines: true
  auto_stop_machines: true
  min_machines_running: 1
  processes:
    - app